name: CI/CD Workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:


jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./bin/Release/
  
  publish:
    name: Publish to NuGet
    runs-on: windows-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Pack NuGet Package
        run: dotnet pack --no-build --configuration Release --output ${{ github.workspace }}/nupkg --source ./build-output

      - name: Publish to NuGet
        run: dotnet nuget push ${{ github.workspace }}/nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json